languageCode = "en-us"
title = "Welcome to the Thunderdome"
baseurl = "http://example.org/"
theme = "prologue"

[params]
  name = "Caleb Brady"
  description = "Digiologist"
  copyright = "Untitled."

[[params.social]]
  medium = "twitter"
  icon = "twitter"
  link = "https://twitter.com/xenapwns"

[[params.social]]
  medium = "facebook"
  icon = "facebook"
  link = "https://www.facebook.com/bad1906"

[[params.social]]
  medium = "github"
  icon = "github"
  link = "https://github.com/brady1906"

  [[params.social]]
  medium = "instagram"
  icon = "instagram"
  link = "https://www.instagram.com/cjbdigsrocks/"

[[params.social]]
  medium = "email"
  icon = "envelope"
  link = "mailto:xbadx1906@gmail.com"

# Portfolio column one

[[params.portfolio1]]
  title = "Ipsum Feugiat"
  alt = ""
  source = "img/pic02.jpg"
  url = "#"

[[params.portfolio1]]
  title = "Rhoncus Semper"
  alt = ""
  source = "img/pic03.jpg"
  url = "#"

# Portfolio column two

[[params.portfolio2]]
  title = "Magna Nullam"
  alt = ""
  source = "img/pic04.jpg"
  url = "#"

[[params.portfolio2]]
  title = "Natoque Vitae"
  alt = ""
  source = "img/pic05.jpg"
  url = "#"

# Portfolio column 3

[[params.portfolio3]]
  title = "Dolor Penatibus"
  alt = ""
  source = "img/pic06.jpg"
  url = "#"

[[params.portfolio3]]
  title = "Orci Convallis"
  alt = ""
  source = "img/pic07.jpg"
  url = "#"
